from marshmallow import Schema, fields, validate, EXCLUDE

class PlantSchema(Schema):
    class Meta:
        unknown = EXCLUDE  # Ignore fields that are not explicitly defined in the schema

    id = fields.Int(required=True)
    common_name = fields.Str(required=True)
    scientific_name = fields.List(fields.Str(), required=False)
    other_name = fields.List(fields.Str(), required=False)
    family = fields.Str(allow_none=True)
    origin = fields.List(fields.Str(), required=False)
    type = fields.Str(required=False)
    dimension = fields.Str(required=False)
    dimensions = fields.Dict(required=False)
    cycle = fields.Str(required=False)
    watering = fields.Str(required=False)
    sunlight = fields.List(fields.Str(), required=False)
    propagation = fields.List(fields.Str(), required=False)
    hardiness = fields.Dict(required=False)
    hardiness_location = fields.Dict(required=False)
    growth_rate = fields.Str(required=False)
    drought_tolerant = fields.Bool(required=False)
    salt_tolerant = fields.Bool(required=False)
    thorny = fields.Bool(required=False)
    invasive = fields.Bool(required=False)
    tropical = fields.Bool(required=False)
    indoor = fields.Bool(required=False)
    care_level = fields.Str(required=False)
    pest_susceptibility = fields.List(fields.Str(), required=False)
    flowers = fields.Bool(required=False)
    flowering_season = fields.Str(allow_none=True, required=False)
    flower_color = fields.Str(required=False)
    cones = fields.Bool(required=False)
    fruits = fields.Bool(required=False)
    edible_fruit = fields.Bool(required=False)
    edible_fruit_taste_profile = fields.Str(required=False)
    fruit_nutritional_value = fields.Str(required=False)
    fruit_color = fields.List(fields.Str(), required=False)
    harvest_season = fields.Str(allow_none=True, required=False)
    leaf = fields.Bool(required=False)
    leaf_color = fields.List(fields.Str(), required=False)
    edible_leaf = fields.Bool(required=False)
    cuisine = fields.Bool(required=False)
    medicinal = fields.Bool(required=False)
    poisonous_to_humans = fields.Bool(required=False)
    poisonous_to_pets = fields.Bool(required=False)
    description = fields.Str(required=False)
    default_image = fields.Dict(required=False)
    care_guides = fields.Str(required=False)
    volume_water_requirement = fields.List(fields.Str(), required=False)
    depth_water_requirement = fields.Dict(required=False)
    pruning_month = fields.List(fields.Str(), required=False)
    pruning_count = fields.List(fields.Str(), required=False)
    watering_period = fields.Str(allow_none=True, required=False)
    watering_general_benchmark = fields.Dict(required=False)
    maintenance = fields.Str(allow_none=True, required=False)
    plant_anatomy = fields.List(fields.Dict(), required=False)
    seeds = fields.Int(required=False)
    other_images = fields.Str(required=False)
